# Cloudflare Pages configuration with Backblaze B2
name = "corabooks"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# KV namespaces for metadata storage
[[kv_namespaces]]
binding = "CORABOOKS_KV"
id = "282de9a3368549c494f082ffe478efb6"
preview_id = "282de9a3368549c494f082ffe478efb6"

# Environment variables for Backblaze B2 (to be set in Cloudflare dashboard)
# B2_APPLICATION_KEY_ID = "your-b2-key-id"
# B2_APPLICATION_KEY = "your-b2-application-key" 
# B2_BUCKET_ID = "your-b2-bucket-id"
# B2_BUCKET_NAME = "your-b2-bucket-name"