# Cloudflare Pages configuration with Backblaze B2
name = "corabooks"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# KV namespaces for metadata storage
[[kv_namespaces]]
binding = "CORABOOKS_KV"
id = "282de9a3368549c494f082ffe478efb6"
preview_id = "282de9a3368549c494f082ffe478efb6"

# Environment variables for Backblaze B2
[env.production.vars]
B2_APPLICATION_KEY_ID = "005377ddf5f41040000000001"
B2_APPLICATION_KEY = "K005P7S++jG0dxNkYwmEJARRmurnui0I"
B2_BUCKET_ID = "733717fdcd9f857f94910014"
B2_BUCKET_NAME = "corabooks-files"

[env.preview.vars]
B2_APPLICATION_KEY_ID = "005377ddf5f41040000000001"
B2_APPLICATION_KEY = "K005P7S++jG0dxNkYwmEJARRmurnui0I"
B2_BUCKET_ID = "733717fdcd9f857f94910014"
B2_BUCKET_NAME = "corabooks-files"